<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Oxygen.Domain\Oxygen.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="7.2.0" />
    </ItemGroup>

</Project>
