events { }

http {
  upstream helium {
    server snowflake-helium.snowye.dev:80;
  }

  upstream carbon {
    server snowflake-carbon.snowye.dev:80;
  }

  upstream oxygen {
    server snowflake-oxygen.snowye.dev:80;
  }

  upstream gold {
    server snowflake-gold.snowye.dev:80;
  }

  server {
    listen 80;

    # HTTP for helium
    location /auth {
      proxy_pass http://helium;
      proxy_set_header Host snowflake-helium.snowye.dev;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto https;
    }

    # HTTP for carbon
    location /score {
      proxy_pass http://carbon;
      proxy_set_header Host snowflake-carbon.snowye.dev;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto https;
    }

    # HTTP for oxygen
    location /loan {
      proxy_pass http://oxygen;
      proxy_set_header Host snowflake-oxygen.snowye.dev;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto https;
    }

    # HTTP for gold
    location /account {
      proxy_pass http://gold;
      proxy_set_header Host snowflake-gold.snowye.dev;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto https;
    }
  }
}