events { }

http {
  upstream helium {
    server snowflake-helium:8080;
  }

  upstream carbon {
    server snowflake-carbon:8081;
  }

  upstream oxygen {
    server snowflake-oxygen:8082;
  }

  upstream gold {
    server snowflake-gold:8083;
  }

  server {
    listen 80;

    # HTTP for helium
    location /auth {
      proxy_pass http://helium;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    # HTTP for carbon
    location /score {
      proxy_pass http://carbon;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    # HTTP for oxygen
    location /loan {
      proxy_pass http://oxygen;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    # HTTP for gold
    location /account {
      proxy_pass http://gold;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
