env: local
http:
  port: 8080
  secure: false
grpc:
  port: 50050
security:
  jwt_secret: super-secret-key
  refresh_secret: super-refresh-secret
  jwt_issuer: snowflake
db:
  driver: postgres
  connectionString: postgres://snowflake:snowflake@127.0.0.1:5432/helium?sslmode=disable
messaging:
  connectionString: amqp://snowflake:snowflake@localhost:5672
google:
  client_id: ''
  client_secret: ''
  redirect_url: ''

log:
  log_level: info
  encoding: console # json or console
  log_file_name: './storage/logs/server.log'
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true
